- name: configure seconion distributed sensor node
  hosts: SOSensor1
  become: true
  become_method: sudo
  vars_files: /ansible/secrets.yml

  tasks:
        - name: Pause for 5 minutes for reboot
          pause:
            minutes: 5

        - name: Fix is_airgap variable for unattended offline install on SO 2.3.140
          lineinfile:
            path: /home/{{SOSensor1.Username}}/SecurityOnion/setup/so-setup
            insertafter: '^automation\=\$2'
            line: 'is_airgap=true'

    - name: Run Security Onion Sensor Setup
      shell: |
        cd "/home/{{SOSensor1.Username}}/SecurityOnion/setup/automation"
        sudo "/home/{{SOSensor1.Username}}/SecurityOnion/setup/so-setup network distributed-airgap-manager"
      ignore_errors: yes
      become: true
